version: "3.8"
services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - TZ=${TZ:-Asia/Tokyo}
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - laravel

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: mysql2
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: laravel
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

# Volumes
volumes:
    mysql-data:
        driver: local

# Networks
networks:
    laravel:
        driver: bridge
